[application]

# App (Project) Name
name = "tic-tac-toe-rs"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "public"

[web.app]
[web.watcher]
[web.resource]
[web.resource.dev]
[bundle]
icon = ["public/icon.png"]
