name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Nix
      - name: Setup Nix
        uses: aldoborrero/use-nix-action@v4
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          use_nix_profile: true
      - name: Check installed direnv tools
        run: which act

      # Rust
      - name: Setup Rust
        uses: actions/checkout@v2
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
      - name: Audit
        run: cargo audit

